// Generated by https://quicktype.io

export interface Account {
    dbid:          number;
    client_id:     number;
    amount:        number;
    init_vig:      string;
    fin_vig:       string;
    currency:      number;
    account_type:  number;
    status:        number;
    user_registry: string;
    user_modified: string;
}
