// Generated by https://quicktype.io

export interface Account {
    dbid:          number;
    clientId:     number;
    amount:        number;
    init_vig:      Date;
    fin_vig:       Date;
    currency:      number;
    account_type:  number;
    status:        number;
    user_registry: string;
    user_modified: string;
}
